[2023-09-18T16:01:54.912+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_parser.transform manual__2023-09-18T16:01:47.949453+00:00 [queued]>
[2023-09-18T16:01:54.918+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_parser.transform manual__2023-09-18T16:01:47.949453+00:00 [queued]>
[2023-09-18T16:01:54.919+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-09-18T16:01:54.927+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): transform> on 2023-09-18 16:01:47.949453+00:00
[2023-09-18T16:01:54.936+0000] {standard_task_runner.py:57} INFO - Started process 81 to run task
[2023-09-18T16:01:54.940+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_parser', 'transform', 'manual__2023-09-18T16:01:47.949453+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/dag_parser.py', '--cfg-path', '/tmp/tmpf583ysma']
[2023-09-18T16:01:54.942+0000] {standard_task_runner.py:85} INFO - Job 241: Subtask transform
[2023-09-18T16:01:55.004+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_parser.transform manual__2023-09-18T16:01:47.949453+00:00 [running]> on host 21ebb80fd9c1
[2023-09-18T16:01:55.195+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='oleg' AIRFLOW_CTX_DAG_ID='dag_parser' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-09-18T16:01:47.949453+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-18T16:01:47.949453+00:00'
[2023-09-18T16:01:55.436+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:55.464+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2023-09-18T16:01:56.140+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:56.215+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:56.296+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:56.406+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:56.465+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:56.552+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:56.614+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:56.672+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:56.729+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:56.780+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:56.830+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:56.890+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:56.940+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:56.993+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.050+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.102+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.163+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.217+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.268+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.320+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.370+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.420+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.479+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.534+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.583+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.635+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.686+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.742+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.799+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.862+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.917+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:57.969+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.031+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.097+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.151+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.203+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.256+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.306+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.360+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.414+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.480+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.532+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.583+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.635+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.690+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.751+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.812+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.875+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.940+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:58.999+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:59.050+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:01:59.102+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:02:56.048+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:02:56.059+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2023-09-18T16:02:56.066+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_parser.py", line 210, in transform
    jobs_res = jobs_res.merge(skills, on='skill_lower', how='left')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 9843, in merge
    return merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 148, in merge
    op = _MergeOperation(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 737, in __init__
    ) = self._get_merge_keys()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1221, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 1778, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'skill_lower'
[2023-09-18T16:02:56.095+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_parser, task_id=transform, execution_date=20230918T160147, start_date=20230918T160154, end_date=20230918T160256
[2023-09-18T16:02:56.112+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 241 for task transform ('skill_lower'; 81)
[2023-09-18T16:02:56.156+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-18T16:02:56.183+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
