[2023-09-18T16:06:59.216+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_parser.transform manual__2023-09-18T16:06:53.333334+00:00 [queued]>
[2023-09-18T16:06:59.222+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_parser.transform manual__2023-09-18T16:06:53.333334+00:00 [queued]>
[2023-09-18T16:06:59.223+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-09-18T16:06:59.233+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): transform> on 2023-09-18 16:06:53.333334+00:00
[2023-09-18T16:06:59.240+0000] {standard_task_runner.py:57} INFO - Started process 74 to run task
[2023-09-18T16:06:59.244+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_parser', 'transform', 'manual__2023-09-18T16:06:53.333334+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/dag_parser.py', '--cfg-path', '/tmp/tmplyfh8qwh']
[2023-09-18T16:06:59.246+0000] {standard_task_runner.py:85} INFO - Job 245: Subtask transform
[2023-09-18T16:06:59.297+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_parser.transform manual__2023-09-18T16:06:53.333334+00:00 [running]> on host fe61d4a8eed4
[2023-09-18T16:06:59.467+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='oleg' AIRFLOW_CTX_DAG_ID='dag_parser' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-09-18T16:06:53.333334+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-18T16:06:53.333334+00:00'
[2023-09-18T16:06:59.741+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:06:59.767+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2023-09-18T16:07:00.341+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:00.395+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:00.460+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:00.571+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:00.641+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:00.706+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:00.772+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:00.838+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:00.919+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:00.986+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.037+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.089+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.142+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.208+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.260+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.311+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.374+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.434+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.485+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.536+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.586+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.636+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.690+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.747+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.797+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.847+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.896+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.945+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:01.997+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:02.047+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:02.097+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:02.147+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:02.200+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:02.252+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:02.305+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:02.356+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:02.406+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:02.458+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:02.520+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:02.572+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:02.623+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:02.673+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:02.724+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:02.775+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:02.825+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:02.879+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:03.043+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:03.111+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:03.177+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:03.229+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:58.667+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:58.708+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2023-09-18T16:07:58.741+0000] {base.py:73} INFO - Using connection ID 'postgres_con' for task execution.
[2023-09-18T16:07:58.750+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2023-09-18T16:07:58.767+0000] {python.py:194} INFO - Done. Returned value was:       id_vac              published_at  ... skill_right_name column_not_exist_in_db
0   86566923  2023-09-17T19:14:32+0300  ...                0                  74701
1   86566923  2023-09-17T19:14:32+0300  ...                0                  74702
2   86566923  2023-09-17T19:14:32+0300  ...                0                  74703
3   86472875  2023-09-17T20:23:05+0300  ...         MS Excel                  74704
4   86472875  2023-09-17T20:23:05+0300  ...                0                  74705
..       ...                       ...  ...              ...                    ...
92  86310510  2023-09-17T23:56:43+0300  ...                0                  74793
93  86310510  2023-09-17T23:56:43+0300  ...                0                  74794
94  86821536  2023-09-18T00:37:28+0300  ...                0                  74795
95  86821536  2023-09-18T00:37:28+0300  ...             BPMN                  74796
96  86821536  2023-09-18T00:37:28+0300  ...                0                  74797

[97 rows x 17 columns]
[2023-09-18T16:07:58.834+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_parser, task_id=transform, execution_date=20230918T160653, start_date=20230918T160659, end_date=20230918T160758
[2023-09-18T16:07:58.911+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-18T16:07:58.941+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
